### ISSUE TITLE
User Story: Book a Class

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/namaste-django#10]
As a **User (Client**, I would like **to book a class**, so that **I can attend it.**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** that I am an unregistered user
    **When** I navigate to the Schedule, choose a class and click the "Book now" button
    **Then** I am prompted to create a user account.
-	Acceptance Criteria 2
    **Given** that I am a registered user
    **When** I navigate to the Schedule page, choose a class and click he "Book now" button
    **Then** I am asked to sign in.
-	Acceptance Criteria 3
    **Given** that I am a logged in user
    **When** I navigate to the Schedule, choose a class and click the "Book now" button
    **Then** the site prompts me to fill a suitable form.
-	Acceptance Criteria 4
    **Given** that I am a logged in user
    **When**  submit a valid booking form for a specific class
    **Then** a suitable notification is shown on the page to confirm a successful booking.

### Tasks
-	[x] Task 1 – Provide a "Book now" button in the detail view of each class
-	[x] Task 2 – Make sure the user is registered and logged in before allowing them to book a class
-	[x] Task 3 – Ensure to get all relevant details in the booking form (class day/time/date, user details, waiver signed)
-	[x] Task 4 – Ask the user to confirm that they want to book a specific class
-	[x] Task 5 – Show a suitable notification to confirm that a class has been booked
