### ISSUE TITLE
User Story: Add a Profile Photo in My Account

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/namaste-django#13]
As a **User (Client)**, I would like **to be able to add my profile picture**, so that **my user account feels personalized and truly mine.**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** that I am a logged in user (client)
    **When** I am on My Account page
    **Then** I can upload a profile picture and save it in my profile.

### Tasks
-	[x] Task 1 – Create a default picture to display in each user account, with its place in a template and styling
-	[x] Task 2 – Add the option to upload a picture as the User edits their profile
-	[x] Task 3 – Save the uploaded picture in the Cloudinary account and display each user's personal picture instead of the default one if they did upload their own.
