### ISSUE TITLE
User Story: Ensure Each Client Signs a Waiver

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/namaste-django#22]
As an **Admin**, I would like **to ensure that each client signs a waiver when booking a class*, so that **I can protect the business and my employees from unforeseen issues.**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** that I am an Admin 
    **When** I check clients' booking data
    **Then** I can see that the waiver has been signed for each and every booking.

### Tasks
-	[x] Task 1 – Create a checkbox as part of the booking form - if checked, the User has agreed to conditions outlined in the studio's liability waiver
-	[x] Task 2 – Make checking the box a requirement to book each and every class
-	[x] Task 3 – Provide a link to the waiver so that the User can access it easily
