### ISSUE TITLE
User Story: Create a Class Schedule

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/namaste-django#23]
As an **Admin**, I would like **to create a class schedule**, so that **all information regarding offered classes can be shown on the website.**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** that I am an Admin logged into my account
    **When** I navigate to the Admin panel
    **Then** I can create a class that gets added to the studio schedule.

### Tasks
-	[x] Task 1 – Create the schedule app
-	[x] Task 2 – Create the class model
-	[x] Task 3 – Add classes in the Admin panel
