### ISSUE TITLE
User Story: Edit a Staff Account

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/namaste-django#27]
As an **Admin**, I would like **to be able to edit a teacher's account**, so that **their profile photo and bio always look professional and are up to date.**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** that I am a logged in Admin
    **When** I navigate to the admin panel
    **Then** I can choose the option "Edit" for each staff (teacher) account
-	Acceptance Criteria 2
    **Given** that I am a logged in Admin
    **When** I navigate to the admin panel, and choose "Edit" next to a staff account
    **Then** I can add/edit/delete a profile photo and a bio.
-	Acceptance Criteria 3
    **Given** that I am a logged in Admin
    **When** I edit a staff account in any way (by adding/updating/deleting a photo or a bio)
    **Then** I can confirm the changes with a "Save" button.
-	Acceptance Criteria 4
    **Given** that I am a logged in Admin
    **When** I edit a staff account and confirm the changes by clicking "Save"
    **Then** I receive a notification that my changes to the account have been saved.

### Tasks
-	[ ] Task 1 – Create the option to add a profile photo
-	[ ] Task 2 – Create the option to add a bio
-	[ ] Task 3 – Create the option to edit the profile photo and bio
-	[ ] Task 4 – Create the option to delete the profile photo and bio
