### ISSUE TITLE
User Story: Install Django and Supporting Libraries

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/namaste-django#35]
As a **Developer**, I would like **to set up Django and install the libraries I need**, so that **I can get ready and start developing the project.**

### Tasks
-	[x] Task 1 – Install Django
-	[x] Task 2 – Install dj_database_url psycopg2
-	[x] Task 3 – Install Cloudinary 
-	[x] Task 4 – Create a requirements.txt file
-	[x] Task 5 – Create a Django project
-	[x] Task 6 – Create the first app
