### ISSUE TITLE
User Story: Secure Sensitive Data - API Keys and Secret Keys

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/namaste-django#36]
As a **Developer**, I would like **to set up my development environment correctly**, so that **any sensitive data stays safe and secure.**

### Tasks
-	[x] Task 1 – Create an env.py file to store any API keys and secure keys
-	[x] Task 2 – Adjust the Django code to point to the correct locations for the secret keys
-	[x] Task 3 – Add the env.py file to .gitignore to ensure it does not get pushed to GitHub
