### ISSUE TITLE
User Story: Deploy the Project to Heroku

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/namaste-django#37]
As a **Developer**, I would like **to deploy the project to Heroku early**, so that **I can ensure that everything works correctly and to test frequently in the production environment.**

### Tasks
-	[x] Task 1 – Create a new app in Heroku
-	[x] Task 2 – Add the database to the resources within the Heroku app
-	[x] Task 3 – Add any secret keys/API keys to Config Vars
-	[x] Task 4 – Update the settings.py file (point to the env.py file in development, the os in deployment, the correct database url from Heroku, and the relevant Cloudinary library)
