### ISSUE TITLE
User Story: View teacher's bio

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/namaste-django#4]
As a **User (Client)**, I would like **to read each teacher's short bio**, so that **I can choose a class and an instructor that is the best fit for me.**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** that I am a User (Client)
    **When** I navigate to the Schedule or Class Detail page
    **Then** I can read a short bio for the particular teacher without having to register or log in.

### Tasks
-	[x] Task 1 – Create a link "Show bio" next to each teacher's name in the schedule and class detail 
-	[x] Task 2 – When the link is clicked, show a modal with the bio
-	[x] Task 3 – Make sure the modal can be closed (X button in the top right corner)
-	[x] Task 4 – Make sure that while the modal is shown, other elements of the page cannot be accessed
