### ISSUE TITLE
Edit a future booking (change date)

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/namaste-django#45]
As a **User (Client)**, I would like **to be able to choose a different date for my upcoming booking*, so that **I can feel in charge of my schedule and have the flexibility I need to change my bookings according to my personal needs.**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** that I am a logged in user
    **When** I navigate to the My Bookings page
    **Then** I can see the Edit option next to my upcoming bookings.
-	Acceptance Criteria 2
    **Given** that I am a logged in user
    **When** I click "Edit booking"
    **Then** I can choose one of available dates for this class.
-	Acceptance Criteria 3
    **Given**  that I am a logged in user changing my booking
    **When** I choose a different date and confirm it
    **Then** it is updated in my account and I can see a notification on the website that confirms the change.

### Tasks
-	[x] Task 1 – Add an "Edit" button next to each booking listed on My Bookings page
-	[x] Task 2 – Create a template for the page where the User (Client) can choose another date for the class
-	[x] Task 3 – On a successful submission, show a message that confirms that the booking has been changed
-	[x] Task 4 – If the user chooses a date on which they already have this class booked, show a message that informs them that they had already booked that class (not allowing to take up more than 1 spot in each specific class)
