### ISSUE TITLE
User Story: Create a User (Client) Account

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/namaste-django#5]
As a **User (Client)**, I would like **to create an account**, so that **I can book classes online.**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** that I am an unregistered User (Client)
    **When** I choose the "Sign Up" option
    **Then** I can create my account with an email address and a password.
-	Acceptance Criteria 2
    **Given** that I am an unregistered User (Client)
    **When** I choose the "Sign Up" option
    **Then** I am sent an email that allows me to verify my email and confirm that I want to sign up for an account.

### Tasks
-	[x] Task 1 – Use Django AllAuth so that the user can create an account.
-	[x] Task 2 – Make sure to verify user's email
-	[x] Task 3 – Adjust the verification/confirmation email so that it displays the correct business name instead of example.com
