### ISSUE TITLE
User Story: Run Manual Tests on the Deployed App

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/namaste-django#50]
As a **Developer**, I would like **to run a series of manual tests on the deployed final version of the app**, so that **I can ensure that everything works as expected**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** that I am a Developer who deployed the final version of the application to Heroku
    **When** I run manual tests on the deployed site
    **Then** I can confirm that everything works correctly.

### Tasks
-	[ ] Task 1 – Run tests in various browsers
-	[ ] Task 2 – Run tests on different devices and/or within the Dev Console
-	[ ] Task 3 – Run performance and accessibility tests (Lighthouse)
-	[ ] Task 4 – Check every element of the deployed site and every functionality
