### ISSUE TITLE
User Story: Log out of the User Account

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/namaste-django#7]
As a **User (Client)**, I would like **to be able to log out of my account**, so that **I can make sure my account details are safe.**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** that I am a logged in user
    **When** I click the "log out" button

### Tasks
-	[x] Task 1 – Once the User is logged in, give them the option to log out in the main menu
-	[x] Task 2 – Defensive programming - when user chooses the log out option, ask for confirmation
-	[x] Task 3 – If the user confirms that they want to log out, redirect them to the Homepage with updated navbar (Login/Signup option shown)
