### ISSUE TITLE
User Story: Manage the User (Client) Account

### ISSUE THREAD

**Issue by Agnieszka-21** [Agnieszka-21/namaste-django#8]
As a **User (Client)**, I would like **to be able to add a profile image and edit my account details**, so that **they stay up to date and I am in charge of my profile.**

### Acceptance Criteria
-	Acceptance Criteria 1
    **Given** that I am a logged in user
    **When** I navigate to my Account page
    **Then** I can add/edit/delete suitable profile data.
-	Acceptance Criteria 2
    **Given** that I am a logged in user
    **When** I add/edit/delete my profile data
    **Then** get a notification that confirms my changes.
-	Acceptance Criteria 3
    **Given** that I am a logged in user
    **When** there is an issue with adding/editing/deleting my profile data
    **Then** the site informs me what went wrong.

### Tasks
-	[ ] Task 1 – Give the User control over their profile image, name, email address and password so that they can be updated
-	[ ] Task 2 – When a User tries to make any changes, ask them to confirm that this is what they want to do
-	[ ] Task 3 – Ensure suitable notification is shown whenever a change is made in the account
